export const Colors = {
  registerPrimary: "#334FD7",
  loginPrimary: "#A4DB51",
  background: "#f0f0f0",
  secondaryBackground: "#F3F3F3",
  placeholderBackground: "#f0f0f0",
  selectionBackground: "#F3F3F3",
  pageBackground: "#FFFFFF",
  itemBackground: "#F3F3F3",
  textGray: "#5A5A5A",
  statusPending: "#FE7143",
  statusApproved: "#A4DB51",
  statusDenied: "#EA4B4B",
  screenBackground: "#F9F9F9",
  headerText: "#161616",
  sheetBackground: "#f8f8f8",
  listBackground: "#fff",
  trackingBackground: "rgba(255, 255, 255, 0.9)",
  shadowColor: "#000",
  stopButton: "#ff4444",
  stopButtonText: "white",
  errorText: "#ff4444",
  transparent: "transparent",
  inputText: "#ffffff",
  modalBackground: "rgba(0, 0, 0, 0.5)",
  popupBackground: "#fff",
  popupShadow: "#000",
  popupText: "#161616",
  termsModalBackground: "rgba(0, 0, 0, 0.5)",
  termsBodyBackground: "#F9F9F9",
  termsText: "#161616",
  termsError: "#EC4E4B",
  studentNumber: "#666666",
  progressBar: "#e0e0e0",
  progressFill: "orange",
  searchBarBackground: "#EBEBEB",
  hyperlinkText: "#FFFFFF",
  inputBorder: "#EBEBEB",
  inputLabel: "#4A4A4A",
} as const;

export const Spacing = {
  listSeparator: 10,
} as const;
