name: Code Quality

on:
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/shared-config.yml
    with:
      artifact-name: quality-deps

  quality:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ["eslint", "prettier", "typescript", "jest"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: quality-deps

      - name: Run ESLint
        if: matrix.check == 'eslint'
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier
        if: matrix.check == 'prettier'
        run: npx prettier --check .

      - name: Run TypeScript Check
        if: matrix.check == 'typescript'
        run: npx tsc --noEmit

      - name: Run Jest Tests
        if: matrix.check == 'jest'
        run: |
          npm test -- --coverage
          npm test -- --updateSnapshot

      - name: Upload ESLint report
        if: matrix.check == 'eslint'
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json
          retention-days: 5

      - name: Upload Coverage report
        if: matrix.check == 'jest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 5

      - name: Quality Check Notice
        run: |
          echo "✨ ${{ matrix.check }} check completed!"
          echo "📊 Check the artifacts for detailed results."
