name: Code Quality
on: [pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npx prettier --check .

      - name: SonarCloud Notice
        run: |
          echo "✨ Code quality checks completed!"
          echo "📊 SonarCloud analysis will run automatically."
          echo "🔍 Check your SonarCloud dashboard for results: https://sonarcloud.io/project/overview?id=ST10204902_Peeper-XBCAD"
