name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  checks: write

jobs:
  setup:
    uses: ./.github/workflows/shared-config.yml
    with:
      artifact-name: ci-deps

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Expo
        run: npm install -g expo-cli

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: ci-deps

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
          retention-days: 5

      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: test-results.xml
          reporter: jest-junit
