name: Security Scan
on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run npm audit (Production Only)
        run: npm audit --production --audit-level=high
        
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Peeper-XBCAD"
          path: "."
          format: "HTML"
          args: >
            --failOnCVSS 7
            --suppression suppression.xml
      - name: Upload Security Results
        uses: actions/upload-artifact@v4
        with:
          name: security-results
          path: reports