name: Security Scan
on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run npm audit
        continue-on-error: true
        run: |
          npm audit --omit=dev --audit-level=critical || true
          npm audit --omit=optional --audit-level=critical || true

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        with:
          project: "Peeper-XBCAD"
          path: "."
          format: "HTML"
          out: "reports"
          args: "--failOnCVSS 9 --suppression suppression.xml"

      - name: Upload Security Results
        uses: actions/upload-artifact@v4
        with:
          name: security-results
          path: reports

      - name: Security Scan Notice
        run: |
          echo "🛡️ Security checks completed!"
          echo "📊 Results have been uploaded as artifacts."
          echo "⚠️ Some non-critical vulnerabilities may exist - check the report for details."
