name: Visualize Workflows
on: [workflow_dispatch]

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate workflow visualization
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "workflow-diagram.svg"
          root_path: ".github/workflows"
